package org.vitrivr.cineast.core.features;


import java.util.ArrayList;
import org.vitrivr.cineast.core.color.RGBContainer;

/**
 * This class contains 147 colours which can be used to colour the superpixels.
 */
public class ColorSuperpixel {

  public ArrayList<RGBContainer> colors = new ArrayList<>();

  public final RGBContainer aliceblue = new RGBContainer(240,248,255);
  public final RGBContainer antiquewhite = new RGBContainer(250,235,215);
  public final RGBContainer aqua = new RGBContainer(0,255,255);
  public final RGBContainer aquamarine = new RGBContainer(127,255,212);
  public final RGBContainer azure = new RGBContainer(240,255,255);
  public final RGBContainer beige = new RGBContainer(245,245,220);
  public final RGBContainer bisque = new RGBContainer(255,228,196);
  public final RGBContainer black = new RGBContainer(0,0,0);
  public final RGBContainer blanchedalmond = new RGBContainer(255,235,205);
  public final RGBContainer blue = new RGBContainer(0,0,255);
  public final RGBContainer blueviolet = new RGBContainer(138,43,226);
  public final RGBContainer brown = new RGBContainer(165,42,42);
  public final RGBContainer burlywood = new RGBContainer(222,184,135);
  public final RGBContainer cadetblue = new RGBContainer(95,158,160);
  public final RGBContainer chartreuse = new RGBContainer(127,255,0);
  public final RGBContainer chocolate = new RGBContainer(210,105,30);
  public final RGBContainer coral = new RGBContainer(255,127,80);
  public final RGBContainer cornflowerblue = new RGBContainer(100,149,237);
  public final RGBContainer cornsilk = new RGBContainer(255,248,220);
  public final RGBContainer crimson = new RGBContainer(220,20,60);
  public final RGBContainer cyan = new RGBContainer(0,255,255);
  public final RGBContainer darkblue = new RGBContainer(0,0,139);
  public final RGBContainer darkcyan = new RGBContainer(0,139,139);
  public final RGBContainer darkgoldenrod = new RGBContainer(184,134,11);
  public final RGBContainer darkgray = new RGBContainer(169,169,169);
  public final RGBContainer darkgreen = new RGBContainer(0,100,0);
  public final RGBContainer darkgrey = new RGBContainer(169,169,169);
  public final RGBContainer darkkhaki = new RGBContainer(189,183,107);
  public final RGBContainer darkmagenta = new RGBContainer(139,0,139);
  public final RGBContainer darkolivegreen = new RGBContainer(85,107,47);
  public final RGBContainer darkorange = new RGBContainer(255,140,0);
  public final RGBContainer darkorchid = new RGBContainer(153,50,204);
  public final RGBContainer darkred = new RGBContainer(139,0,0);
  public final RGBContainer darksalmon = new RGBContainer(233,150,122);
  public final RGBContainer darkseagreen = new RGBContainer(143,188,143);
  public final RGBContainer darkslateblue = new RGBContainer(72,61,139);
  public final RGBContainer darkslategray = new RGBContainer(47,79,79);
  public final RGBContainer darkslategrey = new RGBContainer(47,79,79);
  public final RGBContainer darkturquoise = new RGBContainer(0,206,209);
  public final RGBContainer darkviolet = new RGBContainer(148,0,211);
  public final RGBContainer deeppink = new RGBContainer(255,20,147);
  public final RGBContainer deepskyblue = new RGBContainer(0,191,255);
  public final RGBContainer dimgray = new RGBContainer(105,105,105);
  public final RGBContainer dimgrey = new RGBContainer(105,105,105);
  public final RGBContainer dodgerblue = new RGBContainer(30,144,255);
  public final RGBContainer firebrick = new RGBContainer(178,34,34);
  public final RGBContainer floralwhite = new RGBContainer(255,250,240);
  public final RGBContainer forestgreen = new RGBContainer(34,139,34);
  public final RGBContainer fuchsia = new RGBContainer(255,0,255);
  public final RGBContainer gainsboro = new RGBContainer(220,220,220);
  public final RGBContainer ghostwhite = new RGBContainer(248,248,255);
  public final RGBContainer gold = new RGBContainer(255,215,0);
  public final RGBContainer goldenrod = new RGBContainer(218,165,32);
  public final RGBContainer gray = new RGBContainer(128,128,128);
  public final RGBContainer green = new RGBContainer(0,128,0);
  public final RGBContainer greenyellow = new RGBContainer(173,255,47);
  public final RGBContainer grey = new RGBContainer(128,128,128);
  public final RGBContainer honeydew = new RGBContainer(240,255,240);
  public final RGBContainer hotpink = new RGBContainer(255,105,180);
  public final RGBContainer indianred = new RGBContainer(205,92,92);
  public final RGBContainer indigo = new RGBContainer(75,0,130);
  public final RGBContainer ivory = new RGBContainer(255,255,240);
  public final RGBContainer khaki = new RGBContainer(240,230,140);
  public final RGBContainer lavender = new RGBContainer(230,230,250);
  public final RGBContainer lavenderblush = new RGBContainer(255,240,245);
  public final RGBContainer lawngreen = new RGBContainer(124,252,0);
  public final RGBContainer lemonchiffon = new RGBContainer(255,250,205);
  public final RGBContainer lightblue = new RGBContainer(173,216,230);
  public final RGBContainer lightcoral = new RGBContainer(240,128,128);
  public final RGBContainer lightcyan = new RGBContainer(224,255,255);
  public final RGBContainer lightgoldenrodyellow = new RGBContainer(250,250,210);
  public final RGBContainer lightgray = new RGBContainer(211,211,211);
  public final RGBContainer lightgreen = new RGBContainer(144,238,144);
  public final RGBContainer lightgrey = new RGBContainer(211,211,211);
  public final RGBContainer lightpink = new RGBContainer(255,182,193);
  public final RGBContainer lightsalmon = new RGBContainer(255,160,122);
  public final RGBContainer lightseagreen = new RGBContainer(32,178,170);
  public final RGBContainer lightskyblue = new RGBContainer(135,206,250);
  public final RGBContainer lightslategray = new RGBContainer(119,136,153);
  public final RGBContainer lightslategrey = new RGBContainer(119,136,153);
  public final RGBContainer lightsteelblue = new RGBContainer(176,196,222);
  public final RGBContainer lightyellow = new RGBContainer(255,255,224);
  public final RGBContainer lime = new RGBContainer(0,255,0);
  public final RGBContainer limegreen = new RGBContainer(50,205,50);
  public final RGBContainer linen = new RGBContainer(250,240,230);
  public final RGBContainer magenta = new RGBContainer(255,0,255);
  public final RGBContainer maroon = new RGBContainer(128,0,0);
  public final RGBContainer mediumaquamarine = new RGBContainer(102,205,170);
  public final RGBContainer mediumblue = new RGBContainer(0,0,205);
  public final RGBContainer mediumorchid = new RGBContainer(186,85,211);
  public final RGBContainer mediumpurple = new RGBContainer(147,112,219);
  public final RGBContainer mediumseagreen = new RGBContainer(60,179,113);
  public final RGBContainer mediumslateblue = new RGBContainer(123,104,238);
  public final RGBContainer mediumspringgreen = new RGBContainer(0,250,154);
  public final RGBContainer mediumturquoise = new RGBContainer(72,209,204);
  public final RGBContainer mediumvioletred = new RGBContainer(199,21,133);
  public final RGBContainer midnightblue = new RGBContainer(25,25,112);
  public final RGBContainer mintcream = new RGBContainer(245,255,250);
  public final RGBContainer mistyrose = new RGBContainer(255,228,225);
  public final RGBContainer moccasin = new RGBContainer(255,228,181);
  public final RGBContainer navajowhite = new RGBContainer(255,222,173);
  public final RGBContainer navy = new RGBContainer(0,0,128);
  public final RGBContainer oldlace = new RGBContainer(253,245,230);
  public final RGBContainer olive = new RGBContainer(128,128,0);
  public final RGBContainer olivedrab = new RGBContainer(107,142,35);
  public final RGBContainer orange = new RGBContainer(255,165,0);
  public final RGBContainer orangered = new RGBContainer(255,69,0);
  public final RGBContainer orchid = new RGBContainer(218,112,214);
  public final RGBContainer palegoldenrod = new RGBContainer(238,232,170);
  public final RGBContainer palegreen = new RGBContainer(152,251,152);
  public final RGBContainer paleturquoise = new RGBContainer(175,238,238);
  public final RGBContainer palevioletred = new RGBContainer(219,112,147);
  public final RGBContainer papayawhip = new RGBContainer(255,239,213);
  public final RGBContainer peachpuff = new RGBContainer(255,218,185);
  public final RGBContainer peru = new RGBContainer(205,133,63);
  public final RGBContainer pink = new RGBContainer(255,192,203);
  public final RGBContainer plum = new RGBContainer(221,160,221);
  public final RGBContainer powderblue = new RGBContainer(176,224,230);
  public final RGBContainer purple = new RGBContainer(128,0,128);
  public final RGBContainer red = new RGBContainer(255,0,0);
  public final RGBContainer rosybrown = new RGBContainer(188,143,143);
  public final RGBContainer royalblue = new RGBContainer(65,105,225);
  public final RGBContainer saddlebrown = new RGBContainer(139,69,19);
  public final RGBContainer salmon = new RGBContainer(250,128,114);
  public final RGBContainer sandybrown = new RGBContainer(244,164,96);
  public final RGBContainer seagreen = new RGBContainer(46,139,87);
  public final RGBContainer seashell = new RGBContainer(255,245,238);
  public final RGBContainer sienna = new RGBContainer(160,82,45);
  public final RGBContainer silver = new RGBContainer(192,192,192);
  public final RGBContainer skyblue = new RGBContainer(135,206,235);
  public final RGBContainer slateblue = new RGBContainer(106,90,205);
  public final RGBContainer slategray = new RGBContainer(112,128,144);
  public final RGBContainer slategrey = new RGBContainer(112,128,144);
  public final RGBContainer snow = new RGBContainer(255,250,250);
  public final RGBContainer springgreen = new RGBContainer(0,255,127);
  public final RGBContainer steelblue = new RGBContainer(70,130,180);
  public final RGBContainer tan = new RGBContainer(210,180,140);
  public final RGBContainer teal = new RGBContainer(0,128,128);
  public final RGBContainer thistle = new RGBContainer(216,191,216);
  public final RGBContainer tomato = new RGBContainer(255,99,71);
  public final RGBContainer turquoise = new RGBContainer(64,224,208);
  public final RGBContainer violet = new RGBContainer(238,130,238);
  public final RGBContainer wheat = new RGBContainer(245,222,179);
  public final RGBContainer white = new RGBContainer(255,255,255);
  public final RGBContainer whitesmoke = new RGBContainer(245,245,245);
  public final RGBContainer yellow = new RGBContainer(255,255,0);
  public final RGBContainer yellowgreen = new RGBContainer(154,205,50);

  public ColorSuperpixel(){
    colors.add(aliceblue);
    colors.add(antiquewhite);
    colors.add(aqua);
    colors.add(aquamarine);
    colors.add(azure);
    colors.add(beige);
    colors.add(bisque);
    colors.add(black);
    colors.add(blanchedalmond);
    colors.add(blue);
    colors.add(blueviolet);
    colors.add(brown);
    colors.add(burlywood);
    colors.add(cadetblue);
    colors.add(chartreuse);
    colors.add(chocolate);
    colors.add(coral);
    colors.add(cornflowerblue);
    colors.add(cornsilk);
    colors.add(crimson);
    colors.add(cyan);
    colors.add(darkblue);
    colors.add(darkcyan);
    colors.add(darkgoldenrod);
    colors.add(darkgray);
    colors.add(darkgreen);
    colors.add(darkgrey);
    colors.add(darkkhaki);
    colors.add(darkmagenta);
    colors.add(darkolivegreen);
    colors.add(darkorange);
    colors.add(darkorchid);
    colors.add(darkred);
    colors.add(darksalmon);
    colors.add(darkseagreen);
    colors.add(darkslateblue);
    colors.add(darkslategray);
    colors.add(darkslategrey);
    colors.add(darkturquoise);
    colors.add(darkviolet);
    colors.add(deeppink);
    colors.add(deepskyblue);
    colors.add(dimgray);
    colors.add(dimgrey);
    colors.add(dodgerblue);
    colors.add(firebrick);
    colors.add(floralwhite);
    colors.add(forestgreen);
    colors.add(fuchsia);
    colors.add(gainsboro);
    colors.add(ghostwhite);
    colors.add(gold);
    colors.add(goldenrod);
    colors.add(gray);
    colors.add(green);
    colors.add(greenyellow);
    colors.add(grey);
    colors.add(honeydew);
    colors.add(hotpink);
    colors.add(indianred);
    colors.add(indigo);
    colors.add(ivory);
    colors.add(khaki);
    colors.add(lavender);
    colors.add(lavenderblush);
    colors.add(lawngreen);
    colors.add(lemonchiffon);
    colors.add(lightblue);
    colors.add(lightcoral);
    colors.add(lightcyan);
    colors.add(lightgoldenrodyellow);
    colors.add(lightgray);
    colors.add(lightgreen);
    colors.add(lightgrey);
    colors.add(lightpink);
    colors.add(lightsalmon);
    colors.add(lightseagreen);
    colors.add(lightskyblue);
    colors.add(lightslategray);
    colors.add(lightslategrey);
    colors.add(lightsteelblue);
    colors.add(lightyellow);
    colors.add(lime);
    colors.add(limegreen);
    colors.add(linen);
    colors.add(magenta);
    colors.add(maroon);
    colors.add(mediumaquamarine);
    colors.add(mediumblue);
    colors.add(mediumorchid);
    colors.add(mediumpurple);
    colors.add(mediumseagreen);
    colors.add(mediumslateblue);
    colors.add(mediumspringgreen);
    colors.add(mediumturquoise);
    colors.add(mediumvioletred);
    colors.add(midnightblue);
    colors.add(mintcream);
    colors.add(mistyrose);
    colors.add(moccasin);
    colors.add(navajowhite);
    colors.add(navy);
    colors.add(oldlace);
    colors.add(olive);
    colors.add(olivedrab);
    colors.add(orange);
    colors.add(orangered);
    colors.add(orchid);
    colors.add(palegoldenrod);
    colors.add(palegreen);
    colors.add(paleturquoise);
    colors.add(palevioletred);
    colors.add(papayawhip);
    colors.add(peachpuff);
    colors.add(peru);
    colors.add(pink);
    colors.add(plum);
    colors.add(powderblue);
    colors.add(purple);
    colors.add(red);
    colors.add(rosybrown);
    colors.add(royalblue);
    colors.add(saddlebrown);
    colors.add(salmon);
    colors.add(sandybrown);
    colors.add(seagreen);
    colors.add(seashell);
    colors.add(sienna);
    colors.add(silver);
    colors.add(skyblue);
    colors.add(slateblue);
    colors.add(slategray);
    colors.add(slategrey);
    colors.add(snow);
    colors.add(springgreen);
    colors.add(steelblue);
    colors.add(tan);
    colors.add(teal);
    colors.add(thistle);
    colors.add(tomato);
    colors.add(turquoise);
    colors.add(violet);
    colors.add(wheat);
    colors.add(white);
    colors.add(whitesmoke);
    colors.add(yellow);
    colors.add(yellowgreen);
  }

}
