{
 "title": "Cineast",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Docker Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{name=~\"adampro|grafana-cineast|prometheus-cineast|cadvisor\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total{name=~\"adampro|grafana-cineast|prometheus-cineast\"}) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "RAM used / App",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_mem_MB_average{dimension=~\"java|solr|sql\"}",
       "legendFormat": "{{dimension}} {{job}}"
      }
     ]
    },
    {
     "title": "CPU used / App",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_cpu_cpu_time___average{dimension=~\"httpd|java|solr|sql\"}",
       "legendFormat": "{{dimension}} {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker IO / HW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bytes Written to FS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_writes_bytes_total{name=~\"adampro|grafana-cineast|prometheus-cineast|cadvisor\"}) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Storage Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{name=~\"adampro|grafana-cineast|prometheus-cineast|cadvisor\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Bytes Read from FS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_reads_bytes_total{name=~\"adampro|grafana-cineast|prometheus-cineast|cadvisor\"}) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPUs",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 2, "x": 12, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "engine_daemon_engine_cpus_cpus" }
     ]
    },
    {
     "title": "Memory",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 2, "x": 14, "y": 9 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "engine_daemon_engine_memory_bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Cineast Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Execution Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "cineast_retrievaltask{quantile=\"0.5\"}",
       "legendFormat": "{{Retriever}}"
      }
     ]
    },
    {
     "title": "Feature Processing Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "cineast_feature_process_time{quantile=\"0.5\"}",
       "legendFormat": "{{Extractor}}"
      }
     ]
    },
    {
     "title": "Database Ping",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "cineast_dbping{quantile=\"0.5\"}",
       "legendFormat": "0.5 Quantile"
      },
      {
       "expr": "cineast_dbping{quantile=\"0.9\"}",
       "legendFormat": "0.9 Quantile"
      }
     ]
    }
   ]
  },
  {
   "title": "Import Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Import Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "cineast_importtask_count", "legendFormat": "{{Taskname}}" }
     ]
    },
    {
     "title": "Import Processing Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "cineast_importtask{quantile=\"0.5\"}",
       "legendFormat": "{{Taskname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Netdata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_system_cpu_percentage_average{dimension=~\"user|system|iowait\"}",
       "legendFormat": "{{dimension}} {{job}}"
      }
     ]
    },
    {
     "title": "RAM used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_system_ram_MB_average{dimension=~\"cached|free|used\"}",
       "legendFormat": "{{dimension}} {{job}}"
      }
     ]
    },
    {
     "title": "System load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "netdata_system_load_load_average",
       "legendFormat": "{{dimension}} {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Cineast Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_memory_pool_bytes_used" }
     ]
    },
    {
     "title": "Heap used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\",}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extraction API Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Submitted Paths",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cineast_submitted_paths" }
     ]
    },
    {
     "title": "Paths in Extraction Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cineast_paths_in_queue_0" }
     ]
    }
   ]
  }
 ]
}